sudo: required
services:
 - docker

before_install:
 - docker build -t lienejansone/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true lienejansone/react-test npm test

after_success:
 - docker build -t lienejansone/multi-client ./client
 - docker build -t lienejansone/multi-server ./server
 - docker build -t lienejansone/multi-nginx ./nginx
 - docker build -t lienejansone/multi-worker ./worker
 # Push images to dockerhub
 - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
 - docker push lienejansone/multi-client
 - docker push lienejansone/multi-server
 - docker push lienejansone/multi-nginx
 - docker push lienejansone/multi-worker

deploy:
 edge: true
 provider: elasticbeanstalk
 region: "eu-west-1"
 app: "multi-docker"
 env: "MultiDocker-env"
 bucket_name: "elasticbeanstalk-eu-west-1-932180125438"
 bucket_path: "docker-multi"
 on:
  branch: master
 access_key_id: $aws_access_key
 secret_access_key: $aws_secret_key
